version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  python-app:
    build: .
    container_name: python-app-container
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python3 /app/app.py

volumes:
  mongo-data:
